version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16 # or a specific version like pgvector/pgvector:0.7.0-pg16
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: